// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Orchestrator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Orchestrator.Models.AgentNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedWorkloadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedWorkloadVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PollingIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .IsUnique();

                    b.HasIndex("AgentSecret")
                        .IsUnique();

                    b.HasIndex("AssignedWorkloadId");

                    b.HasIndex("Status");

                    b.ToTable("AgentNodes");
                });

            modelBuilder.Entity("Orchestrator.Models.AgentPackage", b =>
                {
                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalledVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AgentId", "PackageId");

                    b.ToTable("AgentPackages");
                });

            modelBuilder.Entity("Orchestrator.Models.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BinaryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallerFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "Version")
                        .IsUnique();

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("Orchestrator.Models.EnrollmentToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsedByAgentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.ToTable("EnrollmentTokens");
                });

            modelBuilder.Entity("Orchestrator.Models.Workload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkloadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkloadName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkloadId", "Version")
                        .IsUnique();

                    b.ToTable("Workloads");
                });

            modelBuilder.Entity("Orchestrator.Models.WorkloadPackage", b =>
                {
                    b.Property<string>("WorkloadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkloadVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostInitSteps")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreInitSteps")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkloadId", "WorkloadVersion", "PackageId");

                    b.HasIndex("PackageId", "PackageVersion");

                    b.ToTable("WorkloadPackages");
                });

            modelBuilder.Entity("Orchestrator.Models.WorkloadRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkloadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkloadVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkloadId", "WorkloadVersion");

                    b.ToTable("WorkloadRuns");
                });

            modelBuilder.Entity("Orchestrator.Models.WorkloadRunStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("WorkloadRunSteps");
                });

            modelBuilder.Entity("Orchestrator.Models.AgentNode", b =>
                {
                    b.HasOne("Orchestrator.Models.Workload", "Workload")
                        .WithMany()
                        .HasForeignKey("AssignedWorkloadId")
                        .HasPrincipalKey("WorkloadId");

                    b.Navigation("Workload");
                });

            modelBuilder.Entity("Orchestrator.Models.AgentPackage", b =>
                {
                    b.HasOne("Orchestrator.Models.AgentNode", "Agent")
                        .WithMany("InstalledPackages")
                        .HasForeignKey("AgentId")
                        .HasPrincipalKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Orchestrator.Models.WorkloadPackage", b =>
                {
                    b.HasOne("Orchestrator.Models.Artifact", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId", "PackageVersion")
                        .HasPrincipalKey("PackageId", "Version")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orchestrator.Models.Workload", "Workload")
                        .WithMany("Packages")
                        .HasForeignKey("WorkloadId", "WorkloadVersion")
                        .HasPrincipalKey("WorkloadId", "Version")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Workload");
                });

            modelBuilder.Entity("Orchestrator.Models.WorkloadRun", b =>
                {
                    b.HasOne("Orchestrator.Models.AgentNode", null)
                        .WithMany("Runs")
                        .HasForeignKey("AgentId")
                        .HasPrincipalKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orchestrator.Models.Workload", "Workload")
                        .WithMany()
                        .HasForeignKey("WorkloadId", "WorkloadVersion")
                        .HasPrincipalKey("WorkloadId", "Version")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workload");
                });

            modelBuilder.Entity("Orchestrator.Models.WorkloadRunStep", b =>
                {
                    b.HasOne("Orchestrator.Models.WorkloadRun", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Orchestrator.Models.AgentNode", b =>
                {
                    b.Navigation("InstalledPackages");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("Orchestrator.Models.Workload", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Orchestrator.Models.WorkloadRun", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
