// <auto-generated />
using System;
using DeploymentPoC.Orchestrator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeploymentPoC.Orchestrator.Migrations
{
    [DbContext(typeof(InstallerDbContext))]
    [Migration("20260415031219_InitialCanonicalEntities")]
    partial class InitialCanonicalEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.AssignmentLeaseEntity", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastAckedSequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastHeartbeatUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TtlSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignmentId");

                    b.HasIndex("LeaseId")
                        .IsUnique();

                    b.ToTable("AssignmentLeases");
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.ConfigSnapshotEntity", b =>
                {
                    b.Property<Guid>("ConfigSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntegrityHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigSnapshotId");

                    b.HasIndex("JobId", "NodeId", "PackageId", "CapturedAtUtc");

                    b.ToTable("ConfigSnapshots");
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestPackageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestTargetVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReasonCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetNodeIdsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.JobStepEntity", b =>
                {
                    b.Property<Guid>("JobStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReasonCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelemetryRef")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("JobStepId");

                    b.HasIndex("JobId", "Sequence")
                        .IsUnique();

                    b.ToTable("JobSteps");
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.NodeEntity", b =>
                {
                    b.Property<Guid>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NodeId");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.JobStepEntity", b =>
                {
                    b.HasOne("DeploymentPoC.Orchestrator.Data.Entities.JobEntity", "Job")
                        .WithMany("Steps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.JobEntity", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
