// <auto-generated />
using System;
using DeploymentPoC.Orchestrator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeploymentPoC.Orchestrator.Migrations
{
    [DbContext(typeof(InstallerDbContext))]
    [Migration("20260415065357_Task3JobIdempotencyAndValidation")]
    partial class Task3JobIdempotencyAndValidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.AssignmentLeaseEntity", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastAckedSequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastHeartbeatUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("TtlSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignmentId");

                    b.HasIndex("JobId");

                    b.HasIndex("LeaseId")
                        .IsUnique();

                    b.ToTable("AssignmentLeases", t =>
                        {
                            t.HasCheckConstraint("CK_AssignmentLeases_LastAckedSequence", "\"LastAckedSequence\" >= 0");

                            t.HasCheckConstraint("CK_AssignmentLeases_State", "\"State\" IN ('Assigned','Released','Expired')");

                            t.HasCheckConstraint("CK_AssignmentLeases_TtlSeconds", "\"TtlSeconds\" > 0");
                        });
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.ConfigSnapshotEntity", b =>
                {
                    b.Property<Guid>("ConfigSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntegrityHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigSnapshotId");

                    b.HasIndex("NodeId");

                    b.HasIndex("JobId", "NodeId", "PackageId", "CapturedAtUtc");

                    b.ToTable("ConfigSnapshots");
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyRequestHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestPackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestTargetVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReasonCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetNodeIdsCsv")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Jobs", t =>
                        {
                            t.HasCheckConstraint("CK_Jobs_Mode", "\"Mode\" IN ('install','upgrade','rollback','modify','cancel')");

                            t.HasCheckConstraint("CK_Jobs_State", "\"State\" IN ('Queued','Running','Completed','Failed','Cancelled')");
                        });
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.JobStepEntity", b =>
                {
                    b.Property<Guid>("JobStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReasonCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelemetryRef")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("JobStepId");

                    b.HasIndex("JobId", "Sequence")
                        .IsUnique();

                    b.ToTable("JobSteps", t =>
                        {
                            t.HasCheckConstraint("CK_JobSteps_Status", "\"Status\" IN ('Pending','Running','Completed','Failed','Cancelled')");
                        });
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.NodeEntity", b =>
                {
                    b.Property<Guid>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("NodeId");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.ToTable("Nodes", t =>
                        {
                            t.HasCheckConstraint("CK_Nodes_Status", "\"Status\" IN ('Offline','Online')");
                        });
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.PackageEntity", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallArgs")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("PackageId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.AssignmentLeaseEntity", b =>
                {
                    b.HasOne("DeploymentPoC.Orchestrator.Data.Entities.JobEntity", "Job")
                        .WithMany("AssignmentLeases")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.ConfigSnapshotEntity", b =>
                {
                    b.HasOne("DeploymentPoC.Orchestrator.Data.Entities.JobEntity", "Job")
                        .WithMany("ConfigSnapshots")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeploymentPoC.Orchestrator.Data.Entities.NodeEntity", "Node")
                        .WithMany("ConfigSnapshots")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.JobStepEntity", b =>
                {
                    b.HasOne("DeploymentPoC.Orchestrator.Data.Entities.JobEntity", "Job")
                        .WithMany("Steps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.JobEntity", b =>
                {
                    b.Navigation("AssignmentLeases");

                    b.Navigation("ConfigSnapshots");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("DeploymentPoC.Orchestrator.Data.Entities.NodeEntity", b =>
                {
                    b.Navigation("ConfigSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
